#pragma once

static const size_t OVERLAY_NAMES_MP1_COUNT = 0x84;
static const char* OVERLAY_NAMES_MP1[OVERLAY_NAMES_MP1_COUNT] = {
    " ",
    "Chance Time",
    "Slot Machine",
    "Buried Treasure",    
    "Treasure Divers",    
    "Shell Game",    
    "Unused Minigame 0",  
    "Hot Bob-Omb",   
    "Unused Minigame 1",  
    "Pipe Maze",
    "Ghost Guess",   
    "Musical Mushroom",   
    "Pedal Power",   
    "Crazy Cutter",  
    "Face Lift",
    "Whack-a-Plant", 
    "Bash n' Cash",  
    "Bowl Over",
    "Ground Pound",  
    "Balloon Burst", 
    "Coin Block Blitz",   
    "Coin Block Bash",    
    "Skateboard Skamper", 
    "Box Mountain Mayhem",
    "Platform Peril",
    "Teetering Towers",   
    "Mushroom Mixup",
    "Hammer Drop",  
    "Grab Bag",
    "Bobsled Run",  
    "Bumper Balls", 
    "Tightrope Treachery",    
    "Knock Block Tower", 
    "Tipsy Tourney",
    "Bombs Away",   
    "Crane Game",   
    "Flower Shower",
    "Slot Car Derby",    
    "Mario Bandstand",   
    "Desert Dash",  
    "Shy Guy Says", 
    "Limbo Dance",  
    "",   
    "Cast Aways",   
    "Key-pa-way",   
    "Running of the Bulb",    
    "Hot Rope Jump",
    "Handcar Havoc",
    "Deep Sea Divers",   
    "Piranhas Pursuit",  
    "Tug o' War",   
    "Paddle Battle",
    "Bumper Ball Maze",  
    "",   
    "DK's Jungle Adventure",  
    "Peach's Birthday Cake",  
    "Yoshi's Tropical Island",
    "Wario's Battle Canyon",  
    "Luigi's Engine Room",    
    "Mario's Rainbow Castle", 
    "Bowser's Magma Mountain",
    "Eternal Star", 
    "First Map",    
    "",   
    "",   
    "",
    "",
    "",
    "",   
    "",   
    "",   
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Opening Cutscene",
    "",
    "",
    "",
    "",
    "Boot Logos",
    "Boot Logos",
    "",
    "",
    "Mushroom Village",
    "Into the Warp Pipe",  // one up
    "Minigame House",
    "Mushroom Shop",
    "Mushroom Bank",
    "Options House",
    "Minigame Instructions",
    "Testing Room", // one up
    "Minigame Island",
    "Minigame Island",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
};

static const size_t OVERLAY_NAMES_MP2_COUNT = 0x73;
static const char* OVERLAY_NAMES_MP2[OVERLAY_NAMES_MP2_COUNT] = {
    "",              
    "Bowser Slots",        
    "Roll Out The Barrels",  
    "Coffin Congestion",   
    "Hammer Slammer",      
    "Give Me a Brake",       
    "Mallet Go Round",      
    "Grab Bag",            
    "Lava Tile Isle",       
    "Bumper Balloon Cars",  
    "Rakin Em In",          
    "Day at the Races",      
    "Hot Rope Jump",        
    "Hot Bob Omb",          
    "Bowl Over",           
    "Rainbow Run",         
    "Crane Game",          
    "Move to the Music",     
    "Bob-omb Barrage",      
    "Look Away",           
    "Shock Drop Or Roll",    
    "Lights Out",          
    "Filet Relay",         
    "Archerival",         
    "Toad Bandstand",      
    "Bobsled Run",         
    "Handcar Havoc",       
    "Ballon Burst",        
    "Sky Pilots",          
    "Speed Hockey",        
    "Cake Factory",        
    "Dungeon Dash",        
    "Magnet Carta",        
    "Face Lift",           
    "ShellShocked",       
    "Crazy Cutters",       
    "Toad In The Box",       
    "Mecha Marathon",      
    "Roll Call",           
    "Abandon Ship",        
    "Platform Peril",      
    "Totem Pole Pound",     
    "Bumper Balls",        
    "Bombs Away",          
    "Tipsy Tourney",       
    "Honeycomb Havoc",     
    "Hexagon Heat",        
    "Skateboard Scamper",  
    "Slot Car Derby",       
    "Shy Guy Says",         
    "Sneak N Snore",        
    "Drivers Ed",          
    "99999",         
    "Looney Lumberjacks",  
    "Dizzy Dancing",       
    "Tile Driver",         
    "Quicksand Cache",     
    "Bowsers Big Blast",    
    "Torpedo Targets",     
    "Destruction Duet",    
    "Deep Sea Salvage",     
    "",
    "Western Land",
    "",
    "",          
    "Pirate Land",
    "Horror Land",          
    "e",          
    "d",          
    "Space Land"       
    "Mini-Game Stadium",           
    "Mystery Land"
    "Rules Land",          
    "",            
    "",            
    "",            
    "",            
    "",            
    "",            
    "",            
    "",            
    "",     
    "",  
    "",            
    "",      
    "", // board initial frame           
    "",            
    "Boot Logos",       
    "Into The Warp Pipe",
    "",
    "",
    "Title Screen And Intro",      
    "Mario Land",
    "Minigame Land",            
    "Minigame Park",        
    "",            
    "",            
    "", // minigame explanation        
    "",            
    "The Play",            
    "",            
    "",            
    "",            
    "Minigame Coaster"
    "Minigame Coaster",
    "",      
    "Results",            
    "",            
    "Credits"             
};


static const size_t OVERLAY_NAMES_MP3_COUNT = 0x81;
static const char* OVERLAY_NAMES_MP3[OVERLAY_NAMES_MP3_COUNT] = {
    "",
    "A Luva e o Anzol", 
    "Quebra-Coco",
    "Ilumi-Nado",
    "Ladeira Pedreira",
    "Gira-Gira",
    "Esconde Onde",
    "Siga em Frente",
    "Tumbora Lá",
    "Rio de Dinheiro",
    "Marola Maluca",
    "Papa Pizza",
    "Tiro no Bowser",
    "Foguetes Infláveis",
    "Hiper-Hidrantes",
    "Colheita Acrobática",
    "Corrida Cósmica",
    "Remoeda",
    "Volta por Cima",
    "Corta-Corta",
    "No Tempo Certo",
    "Grelha Rolante",
    "Arena do Chute",
    "Áses dos Ares",
    "Salta e Ataca",
    "Patinação com Medo",
    "Briga por Chaves",
    "Tacada Certeira",
    "Guarda-Moedas",
    "Organizamão",
    "Imagem Imperfeita",
    "Quebra-Corbeça",
    "Não Deixe o Som Morrer", 
    "M.P.Q.I.",
    "Dança dos Famosos",
    "Circuito Aquático", 
    "Escorrega e Vai",
    "Torre Altíssima",
    "Nado Arriscado",
    "Encana-Dores",
    "Ora, Bolas",
    "Pegando Fogo",
    "Baralho Mortal",
    "A Porta Certa",
    "Upa, Pocotó",
    "Roda a Roda",
    "Tapa na Flor",
    "Pinga em Mim",
    "Vista Curva",
    "Simbora, Cipó",
    "Tiro ao Alvo",   
    "Fim da Linha",  
    "Arremesso de Bowser",
    "Pisa e Pula",
    "Corrida Chocante",
    "Parafuso Frouxo",
    "Multidão Atrapalhada", 
    "Hora da Rasteira",
    "Fuga da Galinha",   
    "Roda de Prêmios",   
    "Bate Aqui!",
    "Estoura-Balão",
    "Presente do Dori",
    "Tubarões Famintos",
    "Marteladas",
    "Batalha Milenar",
    "Roleta do Mascassino",
    "Escada do Mascassino",
    "Caixas do Mascassino",
    "Desafio Doce do Mascassino", 
    "Corrida de Lancha",
    "",
    "Lago Gélido",
    "Grande Mar Blooper",
    "Deserto Ardente",
    "Floresta Florestal",
    "Gruta Medonha",
    "Ilha Waluigi",
    "",
    "Resultados Finais",
    "",
    "",
    "",   
    "",
    "",
    "Resultados do Tabuleiro",
    "",
    "",
    "Logos Iniciais",
    "Menu Debug",
    "",
    "Gate Guy",
    "Arrowhead",
    "Pipesqueak",
    "Blowhard",
    "Mr. Mover",
    "Backtrack",
    "",
    "Duel Result",
    "Duel Result",
    "",
    "",
    "Story Debug",
    "System Error",
    "",
    "Mini-Game Mode",
    "",
    "Story Mode Cutscene",
    "Story Mode Cutscene",
    "Story Mode Cutscene",
    "Story Mode Cutscene",
    "Story Mode Cutscene",
    "",
    "",
    "",
    "",
    "",
    "Abertura",
    "",
    "Caixa de Brinquedos",
    "Estrela de Preparação",
    "Seleção de Arquivos",
    "Abertura",
    "Opçõess",
    "Staff Credits",
    "Story Results",
    "",
    "Menu de Seleção"
};
